### ISSUE TITLE
Could your script use MagiskΔ instead of your rootAVD ?

### ISSUE THREAD

**Issue by 1457384613gh** [newbit1/rootCROS#5]
Could your script use [MagiskΔ](https://github.com/HuskyDG/magisk-files) instead of your rootAVD ?

This could install directly.

**Comment by windowz414** [comment]
Well, [rootAVD](https://github.com/newbit1/rootAVD) is the repository you should've opened this issue on since [it's the one containing Magisk files and such](https://github.com/newbit1/rootAVD/blob/master/Magisk.zip). rootCROS is just [a wrapper that makes it work on rootAVD](https://github.com/newbit1/rootCROS/blob/4e5777f37ad32af24c1b2c47748d4f37bb5429bf/rootCROS.sh#L254&L261).

**Comment by 1457384613gh** [comment]
https://github.com/casualsnek/waydroid_script

I meant something like this.

Magisk Delta in place of Magisk.
